name: twoot on a schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "6 1,4,7,10,13,16,19,22 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@18ac635edf3d6cd3e88d281bceecc25c4dbc1e73
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm start
        env:
          NODE_ENV: "production"
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
